---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rosa-capi.fullname" . }}-secret
  labels:
    {{- include "rosa-capi.labels" . | nindent 4 }}
type: Opaque
data:
  ocmApiUrl: {{ .Values.ocmAPIUrl | default "https://api.openshift.com" | b64enc }}
  ocmToken: {{ .Values.ocmToken | b64enc }}

