{{- if .Values.rbac.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: openshift-capi-management-hook
  namespace: capi-system
subjects:
  - kind: ServiceAccount
    name: openshift-capi-management-hook
    namespace: capi-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: openshift-capi-restart-hook
{{- end }}
