{{- if .Values.rbac.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: capi-kubeadm-control-plane-manager-privileged
  namespace: capi-kubeadm-control-plane-system
subjects:
  - kind: ServiceAccount
    name: capi-kubeadm-control-plane-manager
    namespace: capi-kubeadm-control-plane-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:privileged
{{- end }}

