{{- if .Values.rbac.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: capi-openshift-scc
  namespace: {{ default "capi-system" (.Values.capi).namespace }}
subjects:
  - kind: ServiceAccount
    name: capi-manager
    namespace: {{ default "capi-system" (.Values.capi).namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:nonroot-v2
{{- end }}
